services:
  web_server:
    image: "${IMAGE_NAME}:${TAG}"
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_TOKEN: ${JWT_TOKEN}
    restart: always
