name: Manual Rollback

on:
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  rollback:
    name: Rollback to Previous Image
    runs-on: ubuntu-latest

    steps:
      - name: Execute rollback on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            echo "Checking for rollback file..."
            if [ ! -f ~/rollback_image.txt ]; then
              echo "Rollback file not found. Aborting."
              exit 1
            fi

            echo "Reading previous image tag from rollback file..."
            ROLLBACK_IMAGE=$(cat ~/rollback_image.txt)

            if [ "$ROLLBACK_IMAGE" = "none" ] || [ -z "$ROLLBACK_IMAGE" ]; then
              echo "No rollback image found or it is invalid. Aborting."
              exit 1
            fi

            echo "Logging into Docker Hub..."
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            echo "Pulling rollback image: $ROLLBACK_IMAGE"
            docker pull $ROLLBACK_IMAGE

            echo "Stopping and removing current containers..."
            docker compose -f docker-compose.yml down

            echo "Writing rollback environment..."
            cat <<EOF > .env
            IMAGE_NAME=${ROLLBACK_IMAGE%:*}
            TAG=${ROLLBACK_IMAGE##*:}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            JWT_TOKEN=${{ secrets.JWT_TOKEN }}
            EOF

            echo "Starting rollback container with Docker Compose..."
            docker compose -f docker-compose.yml up -d --remove-orphans

            echo "Rollback successful."
